#
# .swiftlint.yml
#   based on swiftlint 0.42.0
#

# Lint対象から除外
excluded:
  - Pods
  - Carthage
  - Templates
  - SourcePackages
  - apps
  - script
  - build
  - docs
  - ../../Package.swift

# 無効にするデフォルトルール
disabled_rules:
  #- block_based_kvo
  #- class_delegate_protocol
  #- closing_brace
  #- closure_parameter_position
  #- colon
  #- comma
  #- comment_spacing
  #- compiler_protocol_init
  #- computed_accessors_order
  #- control_statement
  #- custom_rules
  #- cyclomatic_complexity
  #- deployment_target
  #- discarded_notification_center_observer
  #- discouraged_direct_init
  #- duplicate_enum_cases
  #- duplicate_imports
  #- dynamic_inline
  #- empty_enum_arguments
  #- empty_parameters
  #- empty_parentheses_with_trailing_closure
  #- file_length
  #- for_where
  - force_cast                          # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  #- force_try
  #- function_body_length
  #- function_parameter_count
  #- generic_type_name
  #- identifier_name
  #- implicit_getter
  #- inclusive_language
  #- inert_defer
  #- is_disjoint
  #- large_tuple
  #- leading_whitespace
  #- legacy_cggeometry_functions
  #- legacy_constant
  #- legacy_constructor
  #- legacy_hashing
  #- legacy_nsgeometry_functions
  #- line_length
  #- mark
  - multiple_closures_with_trailing_closure # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  #- nesting
  #- no_fallthrough_only
  #- no_space_in_method_call
  #- notification_center_detachment
  #- nsobject_prefer_isequal
  #- opening_brace
  #- operator_whitespace
  #- orphaned_doc_comment
  #- private_over_fileprivate
  #- private_unit_test
  #- protocol_property_accessors_order
  #- reduce_boolean
  #- redundant_discardable_let
  #- redundant_objc_attribute
  - redundant_optional_initialization       # 可読性向上のためにnilによる明示的な初期化を許可するため
  #- redundant_set_access_control
  - redundant_string_enum_value             # explicit_enum_raw_valueのルールを優先するため
  #- redundant_void_return
  #- return_arrow_whitespace
  #- shorthand_operator
  #- statement_position
  #- superfluous_disable_command
  - switch_case_alignment                  # 可読性向上のために、アライメントをずらすため
  #- syntactic_sugar
  - todo                                    # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  #- trailing_comma
  #- trailing_newline
  #- trailing_semicolon
  #- trailing_whitespace
  #- type_body_length
  #- type_name
  #- unneeded_break_in_switch
  #- unused_capture_list
  #- unused_closure_parameter
  #- unused_control_flow_label
  #- unused_enumerated
  #- unused_optional_binding
  #- unused_setter_value
  #- valid_ibinspectable
  #- vertical_parameter_alignment
  #- vertical_whitespace
  #- void_return
  #- weak_delegate
  #- xctfail_message

# 有効にするオプトインルール
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  #- conditional_returns_on_newline           # 早期リターンでの1行記述を許可するため
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  #- empty_xctest_method                     # デフォルトで記述されているので、無視する
  - enum_case_associated_values_count
  - expiring_todo
  #- explicit_acl                             # internalは省略可能とするため
  #- explicit_enum_raw_value                  # raw_valueは省略可能とするため
  - explicit_init
  - explicit_self
  #- explicit_top_level_acl                   # internalは省略可能とするため
  #- explicit_type_interface                  # 型推論が効く場合は型の記述を省略可能とするため
  #- extension_access_modifier                  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  - fallthrough
  - fatal_error_message
  #- file_header                                <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  - file_name
  - file_name_no_space
  #- file_types_order                           <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  - first_where
  - flatmap_over_map_reduce
  #- force_unwrapping                           <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  - function_default_parameter_at_end
  #- ibinspectable_in_extension                 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  - identical_operands
  - implicit_return
  #- implicitly_unwrapped_optional              <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  #- indentation_width                        # 改行時のXcodeの自動インデントとズレが発生するため
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  #- missing_docs                             # 暫定的に外す（後ほど書きます）
  - modifier_order
  - multiline_arguments
  #- multiline_arguments_brackets             # 開始と終了行における括弧と引数の同行内記述を許可するため
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  #- multiline_parameters_brackets            # 開始と終了行における括弧とパラメータの同行内記述を許可するため
  - nimble_operator
  - no_extension_access_modifier
  #- no_grouping_extension                   # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  #- prefer_nimble                            # Nimbleは導入していないため
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  #- prohibited_interface_builder             # InterfaceBuilderでのView作成(IBOutlet利用)を可能とするため
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  #- redundant_type_annotation                # 可読性向上のための型の明示的な記述を許可するため
  #- required_deinit                          # deinitの実装は省略可能とするため
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - switch_case_on_newline
  - test_case_accessibility
  - toggle_bool
  - trailing_closure
  #- type_contents_order                       # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  #- unowned_variable_capture                 # ライフサイクルがアプリと一致するモデル層でのunownedキャプチャを許可するため
  - untyped_error_in_catch
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# returnの省略
implicit_return:
  included:
    - getter
    - closure
    #- function

# 主にRxSwiftでのsubscribeをtrailing_closure violationの対象外とする
# see https://github.com/realm/SwiftLint/issues/2661
trailing_closure:
  only_single_muted_parameter: true

# コメントに対しても trailing_whitespace を適用
trailing_whitespace:
  ignores_comments: false

# 1ファイルの行数制限
file_length:
  warning: 600
  error: 1000

# 1行の文字列制限
line_length:
  warning: 200
  error: 300

# 型定義の行数制限
type_body_length:
  warning: 400
  error: 600

# メソッドの行数制限
function_body_length:
  warning: 100
  error: 200

# クロージャの行数制限
closure_body_length:
  warning: 50
  error: 100

# ネスト制限
nesting:
  type_level: 3

# 型の命名制限
type_name:
  min_length: 3
  max_length: 40

# 識別子の命名制限
identifier_name:
  min_length: 2
  excluded:
    - db
    - id
    - vc
    - x
    - y

